---
- hosts: os
  tasks:
  - name: Check whether firewalld is being used on the host
    service_facts:
    register: ansible_facts.services['firewalld.service']['state']
    ignore_errors: yes

  - name: Debug
    debug:
      msg: "the firewalld is started on the host"
    when: ansible_facts.services['firewalld.service']['state'] != "started"

  - name: check whether iptables is being used on the host
    service_facts: 
    register: ansible_facts.services['iptables.service']['state']
    ignore_errors: yes

  - name: Debug
    debug:
      msg: |
           "the iptables is USED on the host" 
           {{ ansible_facts.services['iptables.service']['state'] }}
    when: ansible_facts.services['iptables.service']['state'] == "started"

#############################################################################
#APPLY DEFAULT RULE FOR CHAINS TO DROP PACKETS IF IPTABLES SERVICE IS STARTED
#############################################################################

  - service_facts:
    register: ansible_facts.services['iptables.service']['state']
    ignore_errors: yes
 
  - name: Ensure default deny firewall(IPTABLES) policy for OUTPUT
    iptables:
      chain: INPUT
      policy: DROP
    iptables:
      chain: OUTPUT
      policy: DROP
    iptables:
      chain: FORWARD
      policy: DROP
    when: ansible_facts.services['iptables.service']['state'] == "started"
    register: ansible_facts
  - lineinfile:
      path: /usr/share/cis/tasks-status.yml
      line: "status101: {{ ansible_facts['changed'] }} ###Droping ALL Chain Packets"
      state: present

 
