---
- hosts: all
  tasks:
  - name: Specifying a destination path
    fetch:
      src: /usr/share/cis/tasks-status.yml
      dest: /root/
      flat: yes
  - include_vars:
     file: /root/tasks-status.yml
     name: test

#############################################################################
#APPLY DEFAULT RULE FOR CHAINS TO DROP PACKETS IF IPTABLES SERVICE IS STARTED
#############################################################################

  - service_facts:
    register: ansible_facts.services['iptables.service']['state']
    ignore_errors: yes
 
  - name: Ensure default deny firewall(IPTABLES) policy for OUTPUT
    iptables:
      chain: INPUT
      policy: ACCEPT
    iptables:
      chain: OUTPUT
      policy: ACCEPT
    iptables:
      chain: FORWARD
      policy: ACCEPT
    when: test['status101']

 
