---
- hosts: all
  tasks:
  - debug:
      msg: RollBacking The dataCenter From CIS Deployment

 
- name: Installing the Required Libraries and Packages
  import_playbook: pkg-rollback.yml

- name: Configuring SSH
  import_playbook: ssh_config-rollback.yml

- name: RollBacking Modules' configuration
  import_playbook: modules-rollback.yml

- name: RollBacking Filesystems Hardening process
  import_playbook: mounts-rollback.yml
  
