---
- hosts: all
  name: Starting Roll-Back
  
  tasks:

  - name: roll-back fstab
    shell: ls /usr/share/cis/fstab
    register: fstab_check
    ignore_errors: yes
  - copy: 
     src: /usr/share/cis/fstab
     dest: /etc
     remote_src: yes
    when: fstab_check.stdout != ""

  - name: roll-back grub
    copy: 
      src: /usr/share/cis/grub.cfg
      dest: /boot/grub2
      remote_src: yes

    copy: 
      src: /usr/share/cis/grub
      dest: /etc/default/
      remote_src: yes

  - name: roll-back selinux
    copy:
      src: /usr/share/cis/config
      dest: /etc/selinux
      remote_src: yes
  
  - name: roll-back /usr/lib/systemd/system/emergency.service
    copy: 
      src: /usr/share/cis/emergency.service
      dest: /usr/lib/systemd/system
      remote_src: yes
   
  - name: roll-back /etc/security/limits.conf
    copy:
      src: /usr/share/cis/limits.conf
      dest: /etc/security/
      remote_src: yes

  - name: roll-back kernel params
    copy:
      src: /usr/share/cis/sysctl.conf
      dest: /etc
      remote_src: yes

  - name: Roll-back /etc/issue 
    copy:
      src: /usr/share/cis/issue
      dest: /etc
      remote_src: yes
  - name: roll-back /etc/issue.net
    copy:
      src: /usr/share/cis/issue.net
      dest: /etc/issue.net
      remote_src: yes
  - name: roll-back /etc/motd
    copy:
      src: /usr/share/cis/motd
      dest:  /etc
      remote_src: yes
  - name: roll-back /etc/hosts.allow
    copy:
      src: /usr/share/cis/hosts.allow
      dest: /etc
      remote_src: yes

  - name: roll-back /etc/hosts.deny 
    copy:
      src: /usr/share/cis/hosts.deny
      dest: /etc
      remote_src: yes
  
  - name: reconfigure /etc/dconf/db/gdm.d/*
    shell: ls -d /etc/dconf/db/gdm.d
    register: gdm_dir_check
    ignore_errors: yes
  - copy:
      src: /usr/share/cis/gdm.d
      dest: /etc/dconf/db/gdm.d
      remote_src: yes   
    when: gdm_dir_check.stdout != ""
    
  - name: check ntp configuration
    shell: ls /usr/share/cis/ntp.conf
    register: ntp_file_check
    ignore_errors: yes
  - copy:
      src: /usr/share/cis/ntp.conf
      dest: /etc
      remote_src: yes
    when: ntp_file_check.stdout != "" 

  - name: configure auditd daemon to halt the system when the audit logs are full.
    shell: ls /usr/share/cis/auditd.conf
    register: audit_file_check
    ignore_errors: yes
  - copy:
      src: /usr/share/cis/auditd.conf
      dest: /etc/audit
      remote_src: yes
    when: audit_file_check.stdout != ""

  - name: roll-back /etc/audit/audit.rules
    shell: ls /usr/share/cis/audit.rules
    register: audit_rules_file_check
    ignore_errors: yes

  - copy:
      src: /usr/share/cis/audit.rules
      dest: /etc/audit/
    when: audit_rules_file_check.stdout != ""

  - name: roll-back /etc/syslog-ng/syslog-ng.conf
    shell: ls /usr/share/cis/syslog-ng.conf
    register: file_exist
    ignore_errors: yes

  - copy: 
      src: /usr/share/cis/syslog-ng.conf
      dest: /etc/syslog-ng
    when: file_exist.stdot != ""
    
    
#...
######################
#Roll-Backing packages
#####################
- name: squashfs
  hosts: redhat7
  tasks:
  - name: Specifying a destination path
    fetch:
      src: /usr/share/cis/tasks-status.yml
      dest: /root/
      flat: yes
  - include_vars:
     file: /root/tasks-status.yml
     name: test

  - name: uninstall NTP
    yum:
       name: ntp
       state: absent
    when: test['status1']

  - name: uninstall aide
    yum:
       name: aide
       state: absent
    when: test['status2']
  
  - name: uninstall prelink
    yum:
       name: prelink
       state: absent
    when: test['status3']

  - name: uninstall setroubleshoot
    yum:
       name: setroubleshoot
       state: present
    when: test['status4']
  
  - name: uninstall mcstrans
    yum:
       name: mcstrans
       state: absent
    when: test['status5']


  - name: uninstall libselinux
    yum:
       name: libselinux
       state: absent
    when: test['status6']
  

  - name: uninstall tcp_wrappers
    yum:
       name: tcp_wrappers
       state: absent
    when: test['status7']

  - name: uninstall xorg-x11*
    yum:
       name: xorg-x11*
       state: present
    when: test['status8']

  - name: uninstall ypbind
    yum:
       name: ypbind
       state: present
    when: test['statusr9']


  - name: uninstall rsh
    yum:
       name: rsh
       state: present
    when: test['status10']
  - name: uninstall libselinux
    yum:
       name: talk
       state: present
    when: test['status11']

  - name: uninstall telnet
    yum:
       name: telnet
       state: present
    when: test['status12']

  - name: uninstall 
    yum:
       name: openldap-client
       state: present
    when: test['status13']

  - name: uninstall
    yum:
       name: rsyslog
       state: absent
    when: test['status14']

  - name: uninstall
    yum:
       name: syslog-ng
       state: absent
    when: test['status15']


