---
- hosts: test
  tasks:
    - sysctl:
       name: net.ipv4.ip_forward
       value: '1'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.all.send_redirects
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.default.send_redirects
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.all.accept_source_route
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.default.accept_source_route
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.all.accept_redirects
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.default.accept_redirects
       value: '0'
       sysctl_set: yes
 
    - sysctl:
       name: net.ipv4.conf.all.secure_redirects
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.default.secure_redirects
       value: '0'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.all.log_martians
       value: '1'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.default.log_martians
       value: '1'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.icmp_echo_ignore_broadcasts
       value: '1'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.icmp_ignore_bogus_error_responses
       value: '1'
       sysctl_set: yes

    - sysctl:
       name: net.ipv4.conf.all.rp_filter
       value: '1'
       sysctl_set: yes

    - sysctl: 
       name: net.ipv4.conf.default.rp_filter
       value: '1'
       sysctl_set: yes

    - sysctl:
       name: net.ipv6.conf.all.accept_ra
       value: '0'
       sysctl_set: yes
       ignoreerrors: yes

    - sysctl:
       name: net.ipv6.conf.default.accept_ra
       value: '0'
       sysctl_set: yes
       ignoreerrors: yes

    - sysctl:
       name: net.ipv6.conf.all.accept_redirects
       value: '0'
       sysctl_set: yes
       ignoreerrors: yes

    - sysctl:
       name: net.ipv6.conf.default.accept_redirects
       value: '0'
       sysctl_set: yes
       ignoreerrors: yes

    - sysctl:
       name: net.ipv4.tcp_syncookies
       value: '1'
       sysctl_set: yes
