---
- hosts: test 
  name: Intial setup 
  tasks:
  - name: Needed configuration for Roll-Back
    file:
      path: /usr/share/cis
      state: directory
      owner: root
      group: root
      mode: '0744'
  - file:
      path: /usr/share/cis/tasks-status.yml
      owner: root
      group: root
      mode: '0644'
      state: touch
  - shell: "> /usr/share/cis/tasks-status.yml"


  - name: isntalling "libselinux-python"
    yum:
      name: libselinux-python
      state: present
  - name: setting selinux
    copy:
      src: /etc/selinux/config
      dest: /usr/share/cis
      remote_src: yes
      force: no


  - name: Ensure selinux is enforcing
    selinux:
     policy: targeted
     state: enforcing

