---
- hosts: test
  tasks:

  - debug:
     msg: "Starting to implement CIS standards"
  - debug:
        msg: |
         "Run at: {{ ansible_date_time.date }} / {{ ansible_date_time.time }}  Version: {{ ansible_facts['distribution_version'] }}
          Kernel Version: {{ ansible_facts['kernel'] }}"



- name: intial setup phase
  import_playbook: initial_setup.yml

- name: Backing up the system
  import_playbook: backup.yml


- name: Install required packages
  import_playbook: pkg.yml

- name: Implementing multiple diverse configurations
  import_playbook: world-wide.yml

- name: Service modifications
  import_playbook: service.yml

- name: Filesystems
  import_playbook: filesystems.yml

- name: mounts
  import_playbook: mounts.yml

- name: configure ssh
  import_playbook: ssh_config.yml

- name: configure cron
  import_playbook: config_cron.yml

- name: System Maintenance
  import_playbook: system_maintenance.yml

  
- name: network config
  import_playbook: net_config.yml

- name: modules
  import_playbook: modules.yml

- name: audit
  import_playbook: audit.yml

- name: logs
  import_playbook: logs.yml

- name: Kernel Parameters sysctl
  import_playbook: kernel-params.yml

- name: firewall
  import_playbook: firewall.yml
