---
- name: autofs
  hosts: os
  tasks:
  - name: Specifying a destination path
    fetch:
      src: /usr/share/cis/tasks-status.yml
      dest: /root/
      flat: yes
  - include_vars:
     file: /root/tasks-status.yml
     name: test

  - name: open port
    firewalld:
       service: autofs
       state: disabled
       permanent: yes
    when: test['status1']
