---
- hosts: os
  gather_facts: no 
  tasks:

  - name: adding line in crontab for aide
    cron:
      name: aide check
      weekday: '*'
      minute: 0
      hour: 5
      user: root
      job: "/usr/sbin/aide --check"
      #cron_file: aide_check
  - name: Ensure bootloader password is set
    shell: grep "^GRUB2_PASSWORD" /boot/grub2/grub.cfg
    register: grub_pass
    ignore_errors: yes
  ## grub2-setpassword
  #We Need to set password for the grub
  - debug:
      msg: "######## {{ grub_pass }}######### The grub has no password "
    when: grub_pass.stdout == ""


  - name: Ensure message of the day is configured properly
    shell: egrep '(\\v|\\r|\\m|\\s)' /etc/motd
    register: motd_message
    ignore_errors: yes
    
  - shell: "> /etc/motd"
    when: motd_message.stdout


  - name: Ensure local login warning banner is configured properly
    shell: egrep '(\\v|\\r|\\m|\\s)' /etc/issue
    register: motd_message
    ignore_errors: yes

  - shell: "> /etc/issue"
    when: motd_message.stdout


  - name:  Ensure mail transfer agent is configured for local-only mode
    lineinfile:
      path: /etc/postfix/main.cf 
      regexp: "^inet_interfaces" 
      state: absent
  - lineinfile:
      path: /etc/postfix/main.cf
      line: "inet_interfaces = loopback-only"
      state: present
  - systemd:
      name: postfix
      state: restarted
  
  - name: Ensure root login is restricted to system console
    copy:
      src: /etc/securetty
      dest: /usr/share/cis
      remote_src: yes

  - shell: "> /etc/securetty"
  - name:  Ensure audit logs are not automatically deleted
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: max_log_file_action
      state: absent
  - lineinfile:
      path: /etc/audit/auditd.conf
      line: max_log_file_action = keep_logs
      state: present
