---
- hosts: os
  tasks:
  
  - name: loading isofs module
    shell: lsmod | grep isofs
    register: isofs_check
    ignore_errors: yes

  - shell: "modprobe -n -v isofs"
    register: isofs_loadable
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf CHANGE IN TASK
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install isofs /bin/true
      state: present
      #insertafter: yes
      create: yes
    when: isofs_check.stdout != "" or  isofs_loadable.stdout == "install /bin/true"

##############################
#This playook should be edited
##############################


  
  - name: loading udf module
    shell: lsmod | grep udf
    register: udf_check
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install udf /bin/true
      insertafter: yes
      create: yes
    when: udf_check.stdout == ""

  - name: loading vfat module
    shell: lsmod | grep vfat
    register: vfat_check
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install vfat /bin/true
      insertafter: yes
      create: yes
    when: vfat_check.stdout == ""

  - name: loading dccp module
    shell: lsmod | grep dccp
    register: dccp_check
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install dccp /bin/true
      insertafter: yes
      create: yes
    when: dccp_check.stdout == ""


  - name: loading rds module
    shell: lsmod | grep rds
    register: rds_check
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install rds /bin/true
      insertafter: yes
      create: yes
    when: rds_check.stdout == ""

  - name: loading sctp module
    shell: lsmod | grep sctp
    register: sctp_check
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install sctp /bin/true
      insertafter: yes
      create: yes
    when: sctp_check.stdout == ""

  - name: loading tipc module
    shell: lsmod | grep tipc
    register: tipc_check
    ignore_errors: yes

  - name: adding it in /etc/modprobe.d/CIS.conf
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: install tipc /bin/true
      insertafter: yes
      create: yes
    when: tipc_check.stdout == ""

############################################################################
#editing this playbook to include some filesystems that should NOT be loaded
############################################################################
  - name: Ensure mounting of cramfs filesystems is disabled
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: "install cramfs /bin/true"
      state: present
      create: yes
  - modprobe:
      name: cramfs
      state: absent

  - name: Ensure mounting of freevxfs filesystems is disabled
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: "install freevxfs /bin/true"
      state: present
      create: yes
  - modprobe:
      name: freevxfs
      state: absent

  - name: Ensure mounting of jffs2 filesystems is disabled
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: "install jffs2 /bin/true"
      state: present
      create: yes
  - modprobe:
      name: jffs2
      state: absent

  - name: Ensure mounting of hfs filesystems is disabled
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: "install hfs /bin/true"
      state: present
      create: yes
  - modprobe: 
      name: hfs
      state: absent

  - name: Ensure mounting of hfsplus filesystems is disabled
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: "install hfsplus /bin/true"
      state: present
      create: yes
  - modprobe:
      name: hfsplus
      state: absent

  - name: Ensure mounting of squashfs filesystems is disabled
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      line: "install squashfs /bin/true"
      state: present
      create: yes
  - modprobe:
      name: squashfs
      state: absent

