---
- name: rollback test
  hosts: test
  tasks:
   - name: rollback aide check
     shell: crontab -u root -l 
     register: aide_check

   - debug:
      var: aide_check

   - name: rollback aide crontab
     cron:
      name: "aide crontab"
      state: absent
     when: aide_check.stdout != ''
