---
- hosts: all
  tasks:

  - name: making sure the back-up prerequisites are done
    file:
      path: /usr/share/cis
      state: directory
      owner: root
      group: root
      mode: '0744'
  - file:
      path: /usr/share/cis/tasks-status.yml
      owner: root
      group: root
      mode: '0644'
      state: touch

  - name: collecting service and its data on the host
    service_facts:
    register: myfacts
  
  - debug:
      msg: "myfacts are {{ myfacts }} "

  - debug:
      msg: "the firewalld is started on the host "
    when: myfacts.ansible_facts.services['firewalld.service']['state'] == "running"
 

  - name: check whether iptables is running
    shell: systemctl status iptables.service | grep -i active | cut -d":" -f1
    register: iptables_exist

#############################################################################
#APPLY DEFAULT RULE FOR CHAINS TO DROP PACKETS IF IPTABLES SERVICE IS STARTED
#############################################################################
  
  - debug:
       msg: "######{{ iptables_exist }} "
 
  - name: Ensure default deny firewall(IPTABLES) policy for OUTPUT
    iptables:
      chain: INPUT
      policy: DROP
    iptables:
      chain: OUTPUT
      policy: DROP
    iptables:
      chain: FORWARD
      policy: DROP
    when: iptables_exist['stdout'] == "   Active"
    ignore_errors: yes
    register: ansible_facts

  - name: debugging the status of the task
    debug:
      msg: "the status of the last task {{ ansible_facts['changed'] }} "
  - lineinfile:
      path: /usr/share/cis/tasks-status.yml
      line: "status101: {{ ansible_facts['changed'] }} ###Droping ALL Chain Packets"
      state: present
    ignore_errors: yes

 
