---
- name: CIS playbook
  hosts: os
  tasks:
  - name: making sure the back-up prerequisites are done
    file:
      path: /usr/share/cis
      state: directory
      owner: root
      group: root
      mode: '0744'
  - file:
      path: /usr/share/cis/tasks-status.yml
      owner: root
      group: root
      mode: '0644'
      state: touch

  - name: disable autofs port
    firewalld:
       service: autofs
       state: disabled
       permanent: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status1: {{ ansible_facts['changed'] }}"
        state: present
        create: yes
#####################################
#Secondplaybook
####################################
       
