---
- hosts: localhost
  name: Executing Tasks

  tasks:
  - name: checking the handler 
    debug:
      msg: "Nice to run the hundler"

    notify: 
      - sayhello


  handlers:
  - name: sayhello
    debug:
      msg: "this is the handler"

  tasks: 
  - name: running another task
    debug:
      msg: "i am runnig after the handler"
