- hosts: os
  gather_facts: yes
  tasks:
  - name:
    debug:
      msg: "{{ ansible_date_time.date }}........{{ ansible_date_time.time }} "

  - name: appending word in line
    shell: egrep -i '^password\s+sufficient\s+pam_unix.so' /etc/pam.d/system-auth
    register: check_sys_lvm
    ignore_errors: yes
  - debug:
      msg: "{{ check_sys_lvm }} "


  - name: adding kernel boot parm
    lineinfile:
      path: /etc/pam.d/system-auth
      line: "{{ check_sys_lvm['stdout'] }}"
      state: absent
 
  - shell: "> /usr/share/cis/temp_system-auth"
  - name: write in temp file
    lineinfile:
      path: /usr/share/cis/temp_system-auth
      line: "{{ check_sys_lvm['stdout'] }}"
      state: present
      create: yes
  - shell: cat /usr/share/cis/temp_system-auth | cut -d "\"" -f 2
    register: line

  - debug:
      msg: "{{ line['stdout'] }}"
  - lineinfile:
      path: /etc/pam.d/system-auth
      line: "{{line['stdout']}} remember=5"
      state: present
    
