---
- name: filesystems
  hosts: redhat7 test
  tasks:
  - include_vars:
     file: /root/cis/redhat/file-log.yml
     name: test

  - name: check /tmp
    mount:
      path: "{{ item.mount }}"
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      opts: nodev,nosuid,rw,noexec,relatime
      state: umounted
    loop: "{{ ansible_mounts }}"
    when: test['status2'] and item.mount == "/tmp"



