---
- name: squashfs
  hosts: redhat7
  tasks:
  - include_vars:
     file: /root/cis/redhat/file-log.yml
     name: test
  - name: load module
    modprobe:
       name: squashfs
       state: present
    when: test['status2']

  - name: load module
    modprobe:
       name: udf
       state: present
    when: test['status3']


  - name: load module
    modprobe:
       name: vfat
       state: present
    when: test['status4']


