---
- name: CIS playbook
  hosts: redhat7 test
  tasks:
  - name: disable autofs port
    firewalld:
       service: autofs
       state: disabled
       permanent: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /root/file-log.yml
        line: "status1: {{ ansible_facts['changed'] }}"
        state: present
        create: yes
  - fetch:
      src: /root/file-log.yml
      dest: /root/cis/redhat/
      flat: yes
#####################################
#Secondplaybook
####################################
       
