---
- name: Starting Hardening Solaris10 Operating system 
  hosts: os
  tasks:
    - debug:
         msg: "Run at: {{ ansible_date_time.date }} / {{ ansible_date_time.time }} in machine: {{ ansible_facts['fqdn'] }}"

    - name: Creating a destination for the scripts
      file:
        state: directory
        path: ~/cis
        mode: 0755

    - name: Transfer Hardening scripts
      script: transfer.sh "{{ ansible_facts['default_ipv4']['address'] }}"
      delegate_to: localhost

    - name: preparing scripts
      script: preparing.sh

    - name: Disable Services
      command: "~/cis/solaris-scripts/s1.sh"

    - name: disable services2
      command: "~/cis/solaris-scripts/s2.sh"

    - pause:
        seconds: 10

    - name: Kernel Parameters
      command: "~/cis/solaris-scripts/s3.sh"

    - pause:
        seconds: 3

    - name: Audit
      command: "~/cis/solaris-scripts/s4.sh"

    - pause:
        seconds: 2

    - name: File and Directory permission
      command: "~/cis/solaris-scripts/s5.sh"

    - pause:
        seconds: 2


    - name: System access
      command: "/cis/solaris-scripts/s6.sh"

    - pause:
        seconds: 2


    - name: User Accounts
      command: "~/cis/solaris-scripts/s7.sh"

